[project]
name = "tag-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mujoco>=3.4.0",
    "mujoco-mjx>=3.4.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
